const clientsList = [
  "SPM Communications",
  "Cherney Law Firm, LLC",
  "Dressie Law Firm",
  "Chip Herrington, Attorney at Law",
  "Law Offices of Wenarsky and Goldstein, LLC",
  "Driessen De Rudder Law Office",
  "Tadeo & Silva Law",
  "Welsh & Welsh PC LLO",
  "The Law Offices of Brian J. Cooke",
  "Wosnik Law, LLC",
  "Farnsworth & Murphy, LLC",
  "FairLaw Firm",
  "Chang & Diamond, APC",
  "Kevin C. Martin, Attorney at Law, PLLC",
  "Conklin Law",
  "DangerLaw",
  "Swingle Levin LLC",
  "Welch Gonzalez PLLC",
  "Diamond Legal, PC",
  "Andrew T. Thomas, Attorneys at Law",
  "Manji Law, P.C.",
  "Stanfield Law, LLC",
  "The Law Offices of Ariadne Berrios",
  "The Law Office of Tatiane M. Silva, P.A.",
  "White Oak Wills & Trusts",
  "Law Offices of Mel Coxwell",
  "Sondhi Defence",
  "The Chouhan Law Firm, LLC",
  "Philip Kim Law, P.C.",
  "Abdin Law",
  "Henkels & Baker, PC",
  "Bardazzi Law",
  "The Law Offices of Cheryl S. Davis, P.C.",
  "Scrofano Law PC",
  "Law Offices of Vanessa Ortega Bartsch",
  "Bardol Law Firm",
  "Strickland Webster LLC",
  "The Law Office of James E. Tyner, PLLC",
  "Wood Law Group",
  "Fortis Military Defense, LLC",
  "Frye Law Group",
  "Stiberman Law, P.A.",
  "Peridot Family Law",
  "Wampler & Passanise Criminal Defense Lawyers / Carver & Associates",
  "HP Law, PLLC",
  "Do Law Office",
  "Histon Law PLLC",
  "Valery Nechay Law",
  "Sabbeth Law",
  "Perigon Legal Services",
  "Light of Justice",
  "The Law Office of Paul Black",
  "KC Immigration Lawyers",
  "The Law Office of S. Lamar Gardner",
  "Teranga Law by Cisse-Green, P.C.",
  "Law Office of Rebecca Feigelson",
  "Waltman Employment Law",
  "Amircani Law LLC",
  "Christopher J Kane PC",
  "Planned Exit: Atlanta Estate Planning",
  "Ralls & Ralls Co. L.P.A.",
  "Hutton Tax Solutions",
  "Kairos Law Group, LLC",
  "Rego Law Firm",
  "Mullen Law Firm",
  "Shane Zisman Law",
  "Geller Law",
  "Conrad Legal",
  "Goldbridge Law",
  "Hirsch Law Group",
  "Constellation Marketing",
];

export const CLIENTS = clientsList.sort((a, b) => a.localeCompare(b));
